package com.snap2card.feature.snap2card.domain.model

/** Domain model for a card generated by the backend OCR/AI pipeline. */
data class GeneratedCard(
    val front: String,
    val back: String,
)
